### ISSUE TITLE
feat:  Adding a Markdown text editor and viewer

### ISSUE THREAD

**Issue by abrahamalen** [Muhammed-Rahif/Notepad#124]
Adding an extra feature of **Markdown text editor** and viewer along with this **notepad** will be an added advantage.  

There are many online markdown text editors available but not a tool that provides both a normal notepad option and a markdown editor.  

I thought of adding this feature by a **mode switching option**.

**Comment by Muhammed-Rahif** [comment]
@abrahamalen wanted to collect more details about this feature request!

**Comment by Muhammed-Rahif** [comment]
### How it will be?!
**1. Side by side, Editor on one side, and preview on other side**
![draw](https://user-images.githubusercontent.com/73386156/149624674-95afb4d6-bd26-4c60-affc-bc448b4faaba.png)
**2. Can view one at a time, example like github comment feature.**
![draw1](https://user-images.githubusercontent.com/73386156/149624763-474886b5-e1b5-41c9-ad58-c6e4da0e5cc8.png)

**Comment by abrahamalen** [comment]
My idea is **"side by side"** => Editor on one side and preview on the other, so that users will be able to see **live results** while typing itself.

**Comment by Muhammed-Rahif** [comment]
Hi @abrahamalen,

I'm writing to let you know that due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, the issues related to the old stack are no longer applicable.

#### We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Therefore, I'm closing this issue. If you believe that the issue is still relevant to the current version of the project, please feel free to create a new issue and provide details on how to reproduce the problem.

Thank you, @abrahamalen, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif
