### ISSUE TITLE
fix: Menu Bar error on safari

### ISSUE THREAD

**Issue by Kannav02** [Muhammed-Rahif/Notepad#135]
**Describe the bug :-**
While I was testing this site out on safari , there was this bug , while I was clicking on other options on the menu bar , the scroll down windows for other options like file , edit , mode was not closing 
Since, this a cross platform OS software you are making , I guess it would be better to take account of other browsers as well

**To Reproduce :-**

1. Go to safari
2. Click on https://notepad.rahif.me/
3. Select any one of the options on menu bar for instance home 
4. then select other option on the browser , like view 
5. observe the error

**Screenshots :-**
<img width="1184" alt="Screenshot 2022-02-06 at 11 30 30 PM" src="https://user-images.githubusercontent.com/90309433/152694605-e4656099-c866-42b7-9442-40767ffb27a8.png">

**Desktop (please complete the following information) :-**

- OS: MacOS
- Browser Safari
- Version

**Comment by Muhammed-Rahif** [comment]
Hi @Kannav02,

I'm writing to let you know that due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, the issues related to the old stack are no longer applicable.

#### We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Therefore, I'm closing this issue. If you believe that the issue is still relevant to the current version of the project, please feel free to create a new issue and provide details on how to reproduce the problem.

Thank you, @Kannav02, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif
