### ISSUE TITLE
fix: content unselected  when we click  any menu items from menu bar

### ISSUE THREAD

**Issue by Jaseem-v** [Muhammed-Rahif/Notepad#93]
When we select the contents that we have wrote and click any of the menu items in the menu bar , the selection is gone . This will make difficult to user when user want to use edit options without using keyboard shortcuts.

Also, these bugs should be fixed by this problem: -
- Most of the Edit dropdown buttons aren't working yet on text editor mode such as copy, paste, cut, undo, and goto. This should also be fixed.

**Comment by Muhammed-Rahif** [comment]
@Jaseem-v yeah, me too noticed that :+1:.

**Comment by Muhammed-Rahif** [comment]
Related resources that I found:-
https://stackoverflow.com/questions/15523667/display-selection-when-textarea-loses-focus
https://stackoverflow.com/questions/8438418/css3-how-to-style-the-selected-text-in-textareas-and-inputs-in-chrome

**Comment by Muhammed-Rahif** [comment]
@all-contributors please add @Jaseem-v for bug

**Comment by Muhammed-Rahif** [comment]
Hi @Jaseem-v,

I'm writing to let you know that due to unforeseen circumstances, this project has been inactive for the past few months. We apologize for any inconvenience this may have caused.

We've recently switched the technology stack of this project from ReactJS to NextJS. As a result, the issues related to the old stack are no longer applicable.

#### We've deployed the new version of the app to production, and you can access it at this link: **[https://notepad-dusky.vercel.app/](https://notepad-dusky.vercel.app/)**

I would like to take this opportunity to encourage you to actively contribute to the project. If you have any ideas, feature requests, or bug reports, please don't hesitate to create a new issue or submit a pull request on our [GitHub repository](https://github.com/Muhammed-Rahif/Notepad).

Therefore, I'm closing this issue. If you believe that the issue is still relevant to the current version of the project, please feel free to create a new issue and provide details on how to reproduce the problem.

Thank you, @Jaseem-v, for your understanding and for your interest in this project! Let's work together to bring it back to life.

Best regards,  
Muhammed Rahif
